// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxa3nHZUCzODnu6e9mBrcJBCCZEHZBGK0',
    appId: '1:980400043732:android:99d6204bbc2f18900b2d41',
    messagingSenderId: '980400043732',
    projectId: 'first-project-a76cd',
    storageBucket: 'first-project-a76cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4xa76g8oUOp4sc4A1rrh9Akm2mJbNyiw',
    appId: '1:980400043732:ios:166bf4e95b21a6650b2d41',
    messagingSenderId: '980400043732',
    projectId: 'first-project-a76cd',
    storageBucket: 'first-project-a76cd.firebasestorage.app',
    androidClientId: '980400043732-2navvlc52amct1pfaq1666pnriq02ov4.apps.googleusercontent.com',
    iosClientId: '980400043732-ovctdd1se524r87d6ij3lki5s3rt2trt.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketKcc',
  );
}
